# Generated by Django 5.2.7 on 2025-11-04 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideo',
            old_name='video',
            new_name='file',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='privacy',
            field=models.CharField(default='Public', max_length=50),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='type',
            field=models.CharField(default='video', max_length=50),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
