# Generated by Django 5.2.7 on 2025-11-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_video_uservideo_file_uservideo_privacy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideo',
            old_name='file',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='user',
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
